# The Avengers

In [1]:
import spacy
import os
from spacy import displacy

In [2]:
# get current working directory
cwd = os.getcwd()

filepath = os.path.join(cwd, 'files', 'avengers.txt')

# read avengers text
with open(filepath, 'r') as f:
    text = f.read()
    print(text)

The film's development began when Marvel Studios received a loan from Merrill Lynch in April 2005. After the success of the film Iron Man in May 2008, Marvel announced that The Avengers would be released in July 2011 and would bring together Tony Stark (Downey), Steve Rogers (Evans), Bruce Banner (Ruffalo), and Thor (Hemsworth) from Marvel's previous films. With the signing of Johansson as Natasha Romanoff in March 2009 and Renner as Clint Barton in June 2010, the film was pushed back for a 2012 release. Whedon was brought on board in April 2010 and rewrote the original screenplay by Zak Penn. Production began in April 2011 in Albuquerque, New Mexico, before moving to Cleveland, Ohio in August and New York City in September. The film has more than 2,200 visual effects shots.
The Avengers premiered in Los Angeles on April 11, 2012, and was released in the United States on May 4, as the last film of Phase One of the MCU. The film received praise for Whedon's direction and screenplay, vis

In [3]:
print(len(text))

1706


In [4]:
for idx, string in enumerate(text):
    print(idx, string)

0 
1 T
2 h
3 e
4  
5 f
6 i
7 l
8 m
9 '
10 s
11  
12 d
13 e
14 v
15 e
16 l
17 o
18 p
19 m
20 e
21 n
22 t
23  
24 b
25 e
26 g
27 a
28 n
29  
30 w
31 h
32 e
33 n
34  
35 M
36 a
37 r
38 v
39 e
40 l
41  
42 S
43 t
44 u
45 d
46 i
47 o
48 s
49  
50 r
51 e
52 c
53 e
54 i
55 v
56 e
57 d
58  
59 a
60  
61 l
62 o
63 a
64 n
65  
66 f
67 r
68 o
69 m
70  
71 M
72 e
73 r
74 r
75 i
76 l
77 l
78  
79 L
80 y
81 n
82 c
83 h
84  
85 i
86 n
87  
88 A
89 p
90 r
91 i
92 l
93  
94 2
95 0
96 0
97 5
98 .
99  
100 A
101 f
102 t
103 e
104 r
105  
106 t
107 h
108 e
109  
110 s
111 u
112 c
113 c
114 e
115 s
116 s
117  
118 o
119 f
120  
121 t
122 h
123 e
124  
125 f
126 i
127 l
128 m
129  
130 I
131 r
132 o
133 n
134  
135 M
136 a
137 n
138  
139 i
140 n
141  
142 M
143 a
144 y
145  
146 2
147 0
148 0
149 8
150 ,
151  
152 M
153 a
154 r
155 v
156 e
157 l
158  
159 a
160 n
161 n
162 o
163 u
164 n
165 c
166 e
167 d
168  
169 t
170 h
171 a
172 t
173  
174 T
175 h
176 e
177  
178 A
179 v
180 e
181 n
182 g
183 e
184 r


In [5]:
nlp = spacy.load('en_core_web_md')

In [6]:
doc = nlp(text)
print(doc)

The film's development began when Marvel Studios received a loan from Merrill Lynch in April 2005. After the success of the film Iron Man in May 2008, Marvel announced that The Avengers would be released in July 2011 and would bring together Tony Stark (Downey), Steve Rogers (Evans), Bruce Banner (Ruffalo), and Thor (Hemsworth) from Marvel's previous films. With the signing of Johansson as Natasha Romanoff in March 2009 and Renner as Clint Barton in June 2010, the film was pushed back for a 2012 release. Whedon was brought on board in April 2010 and rewrote the original screenplay by Zak Penn. Production began in April 2011 in Albuquerque, New Mexico, before moving to Cleveland, Ohio in August and New York City in September. The film has more than 2,200 visual effects shots.
The Avengers premiered in Los Angeles on April 11, 2012, and was released in the United States on May 4, as the last film of Phase One of the MCU. The film received praise for Whedon's direction and screenplay, vis

In [7]:
print(len(doc))                                                                     # get the number of tokens in the document

379


In [8]:
def preview_doc(doc, style=None):
    '''
    arg: document

    returns: different parts of speech taggers

    '''
    return displacy.render(doc, style=style)

In [9]:
preview_doc(doc, style='dep')

In [10]:
assert doc[1].text == 'film'                                                        # get the token at index position 1
assert doc[377].text == '.'                                                         # get the token at index position 377
assert doc[3:11].text == 'development began when Marvel Studios received a loan'    # get tokens between index positions 3 and 11

In [11]:
[t.text for t in doc[20:25]]                                                        # iterate over tokens between index positions 20 and 25

['After', 'the', 'success', 'of', 'the']

In [12]:
for idx, token in enumerate(doc):                                                   # return the index of each token in the text
    print(idx, token)

0 The
1 film
2 's
3 development
4 began
5 when
6 Marvel
7 Studios
8 received
9 a
10 loan
11 from
12  
13 Merrill
14 Lynch
15  
16 in
17 April
18 2005
19 .
20 After
21 the
22 success
23 of
24 the
25 film
26  
27 Iron
28 Man
29  
30 in
31 May
32 2008
33 ,
34 Marvel
35 announced
36 that
37  
38 The
39 Avengers
40  
41 would
42 be
43 released
44 in
45 July
46 2011
47 and
48 would
49 bring
50 together
51 Tony
52 Stark
53 (
54 Downey
55 )
56 ,
57 Steve
58 Rogers
59 (
60 Evans
61 )
62 ,
63 Bruce
64 Banner
65 (
66 Ruffalo
67 )
68 ,
69 and
70 Thor
71 (
72 Hemsworth
73 )
74 from
75 Marvel
76 's
77 previous
78 films
79 .
80 With
81 the
82 signing
83 of
84 Johansson
85 as
86 Natasha
87 Romanoff
88 in
89 March
90 2009
91 and
92 Renner
93 as
94 Clint
95 Barton
96 in
97 June
98 2010
99 ,
100 the
101 film
102 was
103 pushed
104 back
105 for
106 a
107 2012
108 release
109 .
110 Whedon
111 was
112 brought
113 on
114 board
115 in
116 April
117 2010
118 and
119 rewrote
120 the
121 original
122 screenplay

In [13]:
from spacy.tokens import Span

doc.set_ents([Span(doc=doc, start=137, end=139, label='GPE')])                 # set the named entity for span between 137 and 139 as Geopolitical entity
ents = list(doc.ents)

print(f'entity name: {ents[0].text}')
print(f'entity label: {ents[0].label_}')

entity name: New Mexico
entity label: GPE


In [14]:
# make a semantic similarity estimate
text_sim1 = doc[167:178]
text_sim2 = doc[205:252]
text_sim3 = doc[252:312]
text_sim4 = doc[312:341]

print(text_sim1)
print('\n', text_sim2)
print('\n', text_sim3)
print('\n', text_sim4)


The Avengers premiered in Los Angeles on April 11

 The film received praise for Whedon's direction and screenplay, visual effects, action sequences, acting, and musical score, and garnered numerous awards and nominations including Academy Award and BAFTA nominations for achievements in visual effects.

 The film grossed over $1.5 billion worldwide, setting numerous box office records and becoming the third-highest-grossing film of all time at the time of its release and the highest-grossing film of 2012, as well as the first Marvel production to generate $1 billion in ticket sales.

 In 2017, The Avengers was featured as one of the 100 greatest films of all time in an Empire magazine poll.


In [15]:
preview_doc(text_sim1, style='dep')

In [16]:
preview_doc(text_sim2, style='dep')

In [17]:
textsim1_textsim2 = text_sim1.similarity(text_sim2)                           # similarity between text 1 and 2
print('Simmilarity: {0:.2%}'.format(textsim1_textsim2))

Simmilarity: 59.31%


In [18]:
textsim3_textsim4 = text_sim3.similarity(text_sim4)                           # similarity between text 3 and 4
print('Simmilarity: {0:.2%}'.format(textsim3_textsim4))

Simmilarity: 92.06%


In [19]:
def get_lca_mat(Doc):
    '''
    argument: Document or Text
    
    returns: the lowest common ancestor matrix of the Doc
    
    '''
    return Doc.get_lca_matrix() 

In [20]:
get_lca_mat(doc)

array([[  0,   1,   1, ...,  -1,  -1,  -1],
       [  1,   1,   1, ...,  -1,  -1,  -1],
       [  1,   1,   2, ...,  -1,  -1,  -1],
       ...,
       [ -1,  -1,  -1, ..., 376, 345,  -1],
       [ -1,  -1,  -1, ..., 345, 377,  -1],
       [ -1,  -1,  -1, ...,  -1,  -1, 378]])

In [21]:
get_lca_mat(text_sim1)

array([[ 0,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 4,  1,  3,  3,  4,  4,  4,  4,  4,  4,  4],
       [ 4,  3,  2,  3,  4,  4,  4,  4,  4,  4,  4],
       [ 4,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 4,  4,  4,  4,  4,  5,  5,  5,  4,  4,  4],
       [ 4,  4,  4,  4,  4,  5,  6,  7,  4,  4,  4],
       [ 4,  4,  4,  4,  4,  5,  7,  7,  4,  4,  4],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  8,  8,  8],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  8,  9,  9],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  8,  9, 10]])

In [22]:
from spacy.attrs import LOWER, POS, ENT_TYPE, IS_ALPHA

np_array = doc.to_array([LOWER, POS, ENT_TYPE, IS_ALPHA])                                   # return the exported attributes as a numpy array
np_array

array([[15924215345000170802,                   92,                    0,
                           0],
       [ 1827453542365867094,                   92,                    0,
                           1],
       [16428057658620181782,                   94,                    0,
                           0],
       ...,
       [ 3842344029291005339,                   97,                    0,
                           0],
       [12646065887601541794,                   97,                    0,
                           0],
       [  908432558851201422,                  103,                    0,
                           0]], dtype=uint64)

In [23]:
for ent in list(doc.ents):
    print(f'Text: {ent.text}; Label: {ent.label_}')                                        # return the named entities in the document

Text: New Mexico; Label: GPE


In [24]:
ents = doc.ents
preview_doc(ents, style='ent')

In [25]:
for sent in list(doc.sents):                                                               # return sentences in the document
    print(sent)

The film's development began when Marvel Studios received a loan from Merrill Lynch in April 2005.
After the success of the film Iron Man in May 2008, Marvel announced that The Avengers would be released in July 2011 and would bring together Tony Stark (Downey), Steve Rogers (Evans), Bruce Banner (Ruffalo), and Thor (Hemsworth) from Marvel's previous films.
With the signing of Johansson as Natasha Romanoff in March 2009 and Renner as Clint Barton in June 2010, the film was pushed back for a 2012 release.
Whedon was brought on board in April 2010 and rewrote the original screenplay by Zak Penn.
Production began in April 2011 in Albuquerque, New Mexico, before moving to Cleveland, Ohio in August and New York City in September.
The film has more than 2,200 visual effects shots.

The Avengers premiered in Los Angeles on April 11, 2012, and was released in the United States on May 4, as the last film of Phase One of the MCU.
The film received praise for Whedon's direction and screenplay, vi

In [26]:
[s.root.text for s in doc.sents]

['began',
 'announced',
 'pushed',
 'brought',
 'began',
 'has',
 'premiered',
 'received',
 'grossed',
 'featured',
 'released',
 '\n\n']